#!/usr/bin/env bash
# Allow incoming traffic via tcp only on port 22, 80 and 443

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow proto tcp from any to any port 22,80,443 comment "Allow access to ssh, http & https via tcp protocol"
echo y | sudo ufw enable
