#!/usr/bin/env bash
# debugging
pkill apache2
chmod u=rw,g=rw,o=rw /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i '1s/^/user nginx;\n/' /etc/nginx/nginx.conf
su - nginx -c "service nginx start"
